'use strict';
const assert=require('node:assert/strict');
const E=require('../engine'),S=require('../skills'),AI=require('../ai');
function game(){const g=E.createGame(['A','B']);g.phase='playing';g.turn=0;g.step='awaitAction';g.players.forEach(p=>{p.hp=30;p.energy=11;});return g;}
function prepare(g,who,digit,energy=11){g.turn=who;g.step='awaitAction';g.controller=-1;g.players[who].skill=digit;g.players[who].energy=energy;}
function cast(g,who,digit,id,energy=11){prepare(g,who,digit,energy);const result=E.actSkill(g,S.SKILLS[digit].findIndex(s=>s.id===id));assert.equal(result.ok,true,result.err);}
function count(p){return p.dummy.alive?1+(p.dummy.reserve||[]).length:0;}
const tests={
 '赌命第二次施放被拒绝，血费倒计时与行动均不改变'(){const g=game();cast(g,0,8,'duming');g.players[0].duming.turnsLeft=1;prepare(g,0,8);const before=E.serializeGame(g);const r=E.actSkill(g,3);assert.match(r.err,/一次/);assert.equal(E.serializeGame(g),before);assert.ok(!AI.legalActions(g).some(a=>a.type==='act'&&a.skillIdx===3));},
 '24点使用扣费前四手数字，成功支付四费并加血'(){const g=game();g.players[1].energy=0;g.players[1].skill=2;cast(g,0,4,'dian24',4);assert.equal(g.players[0].hp,35);assert.equal(g.players[0].energy,0);},
 '24点不会误用扣费后恰好可解的组合'(){const g=game();g.players[1].energy=1;g.players[1].skill=1;let e;for(let v=4;v<=11;v++)if(!S.solve24([v%10,4,1,1])&&S.solve24([(v-4)%10,4,1,1])){e=v;break;}assert.notEqual(e,undefined);cast(g,0,4,'dian24',e);assert.equal(g.players[0].hp,30);},
 '强化与呼吸的施放先后均每层加到2血'(){for(const order of [['qianghua','huxi'],['huxi','qianghua']]){const g=game();for(const id of order)cast(g,0,id==='huxi'?8:6,id);const p=g.players[0],before=p.hp;prepare(g,1,1);E.passTurn(g);assert.equal(p.hp,before+2);}},
 '两层呼吸强化后每回合4血，移除强化后变2血'(){const g=game();const p=g.players[0];p.huxi=2;p.qianghua=true;prepare(g,1,1);E.passTurn(g);assert.equal(p.hp,34);p.qianghua=false;prepare(g,1,1);E.passTurn(g);assert.equal(p.hp,36);},
 '唐化支持多个假人，强化仅队首，按顺序挡致命伤'(){const g=game(),p=g.players[0];cast(g,0,3,'tanghua');for(let i=0;i<3;i++)cast(g,0,0,'jiaren');assert.equal(count(p),3);cast(g,0,0,'jiarenqh');assert.equal(p.dummy.hp,3);assert.deepEqual(p.dummy.reserve,[1,1]);p.hp=1;cast(g,1,1,'quan');assert.equal(p.hp,3);assert.equal(count(p),2);p.hp=1;cast(g,1,1,'quan');assert.equal(p.hp,1);assert.equal(count(p),1);assert.ok(!g.over);},
 '没有唐化仍只能有一个假人，原有空放行为保留'(){const g=game(),p=g.players[0];cast(g,0,0,'jiaren');cast(g,0,0,'jiaren');assert.equal(count(p),1);assert.equal(p.streak,2);assert.equal(g.turn,1);},
 '识破清空整队假人，不交换本体血量'(){const g=game(),p=g.players[1];p.dummy={alive:true,hp:2,castBefore:true,reserve:[3,4]};cast(g,0,9,'shipo',9);assert.equal(count(p),0);assert.equal(p.hp,29);assert.equal(g.players[0].hp,31);assert.equal(g.players[0].energy,6);},
 '识破被无敌抵挡时保留假人，施放者加血加费照常'(){const g=game(),p=g.players[1];p.wudi=true;p.dummy={alive:true,hp:2,castBefore:true,reserve:[3,4]};cast(g,0,9,'shipo',9);assert.equal(count(p),3);assert.equal(p.hp,32);assert.equal(g.players[0].energy,6);},
 '98K连携无视整队假人'(){const g=game();g.players[1].dummy={alive:true,hp:2,castBefore:true,reserve:[3,4]};g.chainCount=3;g.chainDigits=new Set(['san','ba']);cast(g,0,6,'jiubaK');assert.equal(g.winner,0);assert.equal(count(g.players[1]),3);},
 '荆棘造成双方致命伤时先分别触发假人再判胜负'(){const g=game();g.players[0].hp=1;g.players[0].dummy={alive:true,hp:4,castBefore:true,reserve:[]};g.players[1].hp=1;g.players[1].jingji=true;g.players[1].dummy={alive:true,hp:3,castBefore:true,reserve:[2]};cast(g,0,1,'quan');assert.ok(!g.over);assert.equal(g.players[0].hp,4);assert.equal(g.players[1].hp,3);assert.equal(count(g.players[1]),1);},
 '延迟伤害等受伤方真正结束回合，再次行动不提前触发'(){const g=game(),p=g.players[1];cast(g,0,3,'xiaolieyan');assert.equal(p.hp,27);cast(g,1,1,'yi');assert.equal(p.hp,27);assert.equal(p.delayed.length,1);prepare(g,1,1);E.passTurn(g);assert.equal(p.hp,25);assert.equal(p.delayed.length,0);},
 '冰封回合保留基础1费，并在结束时结算延迟伤害'(){const g=game(),p=g.players[1];p.freeze=2;p.energy=2;p.delayed=[{owner:0,dmg:2,desc:'小烈焰',noBonus:true}];prepare(g,0,1);E.passTurn(g);assert.equal(p.energy,3);assert.equal(p.hp,28);assert.equal(p.delayed.length,0);assert.equal(g.turn,0);},
 '受伤方结束先结算DOT，不被下一位的开局治疗救回'(){const g=game(),p=g.players[0],o=g.players[1];p.hp=1;p.jingji=true;p.delayed=[{owner:1,dmg:2,desc:'淬毒',noBonus:true}];o.hp=1;o.huxi=5;E.passTurn(g);assert.ok(g.over);assert.equal(g.result,'draw');assert.equal(o.hp,0);},
 '盈能由非攻击技能蓄能至6，免费八保持不扣净费'(){const g=game(),p=g.players[0];cast(g,0,6,'yingneng',6);assert.equal(p.energy,2);assert.equal(p.yingneng.charge,3);for(let i=0;i<5;i++)cast(g,0,8,'ba',8);assert.equal(p.energy,8);assert.equal(p.yingneng.charge,6);cast(g,0,1,'quan');assert.equal(g.players[1].hp,22);assert.equal(p.yingneng.charge,0);},
 '盈能不因空过或DOT蓄能消耗，普通攻击被盾挡仍消耗'(){const g=game(),p=g.players[0];p.yingneng={active:true,charge:5};p.delayed=[{owner:1,dmg:1,desc:'毒',noBonus:true}];E.passTurn(g);assert.equal(p.yingneng.charge,5);g.players[1].wudi=true;cast(g,0,1,'quan');assert.equal(p.yingneng.charge,0);assert.equal(g.players[1].hp,32);},
 '旧存档兼容假人队列、赌命次数、盈能充能'(){const g=game();delete g.players[0].dummy.reserve;delete g.players[0].dumingUsed;g.players[0].duming.active=true;g.players[0].yingneng={active:true,idle:4};const copy=E.deserializeGame(E.serializeGame(g));assert.deepEqual(copy.players[0].dummy.reserve,[]);assert.equal(copy.players[0].dumingUsed,true);assert.equal(copy.players[0].yingneng.charge,4);},
 'AI搜索不修改假人队列或实际充能'(){const g=game();g.players[0].tanghua=true;g.players[0].dummy={alive:true,hp:2,castBefore:true,reserve:[3,4]};g.players[0].yingneng={active:true,charge:4};const before=E.serializeGame(g);AI.chooseAction(g,0,'hard',60);assert.equal(E.serializeGame(g),before);}
};
for(const [name,test] of Object.entries(tests)){test();console.log('  ✓ '+name);}console.log(`通过 ${Object.keys(tests).length} 项规则校正测试`);
